# Generated by Django 4.0.2 on 2022-05-17 10:21

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Git',
            fields=[
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('salt', models.CharField(default=None, editable=False, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Git',
                'verbose_name_plural': 'Git',
            },
            bases=(app.models.GitAbstract, models.Model),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_path', models.CharField(max_length=150)),
                ('name', models.CharField(blank=True, max_length=300, verbose_name='Название')),
                ('access_log_path', models.CharField(blank=True, max_length=150, verbose_name='Access Logs')),
                ('error_log_path', models.CharField(blank=True, max_length=150, verbose_name='Error Logs')),
                ('env_path', models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='venv path')),
                ('git_path', models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='.git path')),
                ('gunicorn_path', models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Gunicorn path')),
                ('branch_now', models.CharField(default='main', max_length=300, verbose_name='Branch')),
                ('default_git', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_git', to='app.git')),
                ('owner', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='developers', to=settings.AUTH_USER_MODEL, verbose_name='Developers')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проект',
                'ordering': ['-id'],
            },
            bases=(app.models.ProjectAbstract, models.Model),
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_permission', models.PositiveSmallIntegerField(choices=[(1, 'shell'), (2, 'serve'), (3, 'git')])),
                ('user', models.ManyToManyField(related_name='permission', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Права доступа',
                'verbose_name_plural': 'Права доступа',
            },
        ),
    ]
