# Generated by Django 4.0.2 on 2022-03-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_database_options_alter_logs_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='logs',
        ),
        migrations.AddField(
            model_name='project',
            name='access_log_path',
            field=models.CharField(default=1, max_length=150, verbose_name='Access Logs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='error_log_path',
            field=models.CharField(default=1, max_length=150, verbose_name='Error Logs'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Logs',
        ),
    ]
