# Generated by Django 4.0.2 on 2022-04-02 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_gitbranch_project_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='branch',
        ),
        migrations.AddField(
            model_name='gitbranch',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.project'),
        ),
    ]
