# Generated by Django 4.0.2 on 2022-04-02 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_project_branch_gitbranch_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitbranch',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.gitbranch'),
        ),
    ]
