# Generated by Django 4.0.2 on 2022-04-05 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_project_branch_project_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-id'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проект'},
        ),
        migrations.AlterField(
            model_name='project',
            name='data_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.database'),
        ),
    ]
