# Generated by Django 4.0.2 on 2022-04-08 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_git_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='data_base',
        ),
        migrations.DeleteModel(
            name='Database',
        ),
    ]
