# Generated by Django 4.0.2 on 2022-04-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_project_data_base_delete_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='git',
            name='salt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
