# Generated by Django 4.0.2 on 2022-04-10 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_git_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='git',
        ),
    ]
