# Generated by Django 4.0.2 on 2022-04-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_project_git'),
    ]

    operations = [
        migrations.AlterField(
            model_name='git',
            name='salt',
            field=models.CharField(default=None, editable=False, max_length=100, null=True),
        ),
    ]
