# Generated by Django 4.0.2 on 2022-04-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_project_description_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='env_path',
            field=models.CharField(default=None, max_length=300, null=True, verbose_name='venv path'),
        ),
        migrations.AddField(
            model_name='project',
            name='git_path',
            field=models.CharField(default=None, max_length=300, null=True, verbose_name='.git path'),
        ),
    ]
