# Generated by Django 4.0.2 on 2022-04-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_project_git_repo_name_alter_project_env_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gunicorn_path',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Gunicorn path'),
        ),
        migrations.AlterField(
            model_name='project',
            name='access_log_path',
            field=models.CharField(blank=True, max_length=150, verbose_name='Access Logs'),
        ),
        migrations.AlterField(
            model_name='project',
            name='error_log_path',
            field=models.CharField(blank=True, max_length=150, verbose_name='Error Logs'),
        ),
    ]
