# Generated by Django 4.0.2 on 2022-04-23 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_project_gunicorn_path_alter_project_access_log_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='git_repo_name',
        ),
    ]
