# Generated by Django 4.0.2 on 2022-04-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_project_git_repo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='branch',
        ),
        migrations.AddField(
            model_name='project',
            name='branch_now',
            field=models.CharField(default='main', max_length=300, verbose_name='Branch'),
        ),
    ]
