# Generated by Django 4.0.2 on 2022-05-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_permissions_delete_gitbranch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='class_permission',
            field=models.PositiveSmallIntegerField(choices=[(1, 'shell'), (2, 'serve'), (3, 'git')], max_length=150),
        ),
    ]
